//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travis.Console.Commandline {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandlineMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandlineMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Travis.Console.Commandline.CommandlineMessages", typeof(CommandlineMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter {0} for command {1} at position {2}: {3}..
        /// </summary>
        internal static string InvalidCommandParameterDetailedMessage {
            get {
                return ResourceManager.GetString("InvalidCommandParameterDetailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter {0} for command {1} at position {2}..
        /// </summary>
        internal static string InvalidCommandParameterMessage {
            get {
                return ResourceManager.GetString("InvalidCommandParameterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameter should not have any non keyed arguments.
        /// </summary>
        internal static string ParameterKeyedArgumentsOnlyAllowed {
            get {
                return ResourceManager.GetString("ParameterKeyedArgumentsOnlyAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameter should not have any keyed arguments.
        /// </summary>
        internal static string ParameterNoKeyedArgumentsAllowed {
            get {
                return ResourceManager.GetString("ParameterNoKeyedArgumentsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redefinition of parameter {0} at position {1}..
        /// </summary>
        internal static string ParameterRedefinitionMessage {
            get {
                return ResourceManager.GetString("ParameterRedefinitionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameter should have exactly one non keyed argument.
        /// </summary>
        internal static string ParameterSingleArgumentAllowed {
            get {
                return ResourceManager.GetString("ParameterSingleArgumentAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error at position {0}: {1}..
        /// </summary>
        internal static string SyntaxErrorDetailedMessage {
            get {
                return ResourceManager.GetString("SyntaxErrorDetailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error at position {0}..
        /// </summary>
        internal static string SyntaxErrorMessage {
            get {
                return ResourceManager.GetString("SyntaxErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command: {0}
        ///
        ///{1}.
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
    }
}
