//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travis.Console.Commandline.Tokens {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TokenMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TokenMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Travis.Console.Commandline.Tokens.TokenMessages", typeof(TokenMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter argument {0} was already defined..
        /// </summary>
        internal static string CommandlineParameterArgumentDefinedMultipleTimes {
            get {
                return ResourceManager.GetString("CommandlineParameterArgumentDefinedMultipleTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter declaration should start with {0}..
        /// </summary>
        internal static string CommandlineParameterInvalidPrefix {
            get {
                return ResourceManager.GetString("CommandlineParameterInvalidPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter declaration has no name supplied..
        /// </summary>
        internal static string CommandlineParameterNoName {
            get {
                return ResourceManager.GetString("CommandlineParameterNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: Travis.Console.exe learn /game:name
        ///    [/budget:name,argumentlist] [/selectors:name1,...,nameN]
        ///    
        ///    Learns tree for specified game.
        ///  
        ///    Parameters:
        ///      /game - game to learn
        ///        name - name of game to learn
        ///        
        ///      /budget - computational budget (default - budget:iteration,1000)
        ///        name         - name of budget provider
        ///        argumentlist - optional comma-separated argument list specific to
        ///                       particular budget provider. For example:
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpLearn {
            get {
                return ResourceManager.GetString("HelpLearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: Travis.Console.exe COMMAND [arguments]
        ///    
        ///    Available commands:
        ///      help  - shows program or command help
        ///      learn - learns tree model
        ///    
        ///    For detail info call: Travis.Console.exe help COMMAND.
        /// </summary>
        internal static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character &apos;{0}&apos;..
        /// </summary>
        internal static string UnexpectedCharacter {
            get {
                return ResourceManager.GetString("UnexpectedCharacter", resourceCulture);
            }
        }
    }
}
